[package]
name = "rart_zephyr_template_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
heapless = "0.7.10"
rart-rs = { version = "0.0.6", features = ["alloc_rtos"] }
rart-macros = { version = "0.0.3" }
panic-halt = "0.2.0"

[lib]
name = "rart_zephyr_template_rs"
crate-type = ["staticlib"]
